Bug #820037 - sprdroid8.1_trunk_sharkl3_bringup_dev2 engmode compile fail(vendor/sprd/proprietories-source/engmode/eng_hardware_test.c:397: error: undefined reference to '__android_log_print')
[root cause  ] LOCAL_SHARED_LIBRARIES := libcutils liblog
[changes     ] LOCAL_SHARED_LIBRARIES := libcutils liblog
[side effects] no
[self test   ]:yes
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:no
[is there dependence]:no
[confirm dependent commit]:no
[board]:sp9832e_1h10
[test case]:mma ,pass
[reviewers   ] zhiguo.li
[change_type ] bringup --> build_config
[tag_product ] common

Change-Id: I364e51055919fdf68f15630c0c284b041c5585cf